/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface PredefinedWord {
  word: string;
  category: string;
}

export interface PredefinedThemeInfo {
  themeId: string;
  themeName: string;
  icon: string;
  description: string;
  secretWordCandidates: string[];
  words: PredefinedWord[];
}

const TRANSITO_WORDS: PredefinedWord[] = [
  // Veículos (Cars, motorcycles, buses, etc.)
  ...['carro', 'automovel', 'veiculo', 'viatura', 'moto', 'motocicleta', 'caminhao', 'onibus', 'bicicleta', 'trator', 'jipe', 'perua', 'van', 'lambreeta', 'scooter', 'bonde', 'charrete', 'reboque', 'guincho', 'carrinho', 'carreta', 'retroescavadeira', 'ambulancia', 'taxi', 'clube', 'fusca', 'monza', 'opala', 'gol', 'palio', 'uno', 'celta', 'corsa', 'brasilia', 'kombi', 'limusine', 'conversivel', 'esportivo', 'sedan', 'hatch', 'picape', 'furgao', 'cavalinho', 'reboque', 'semitransporte', 'bicicletario', 'jardineira', 'quadriciclo', 'triciclo', 'patinete', 'monociclo', 'blindado', 'tanque', 'batedor', 'carroça', 'coche', 'diligencia', 'bonde', 'fretado', 'circular', 'coletivo', 'escolar', 'vessel', 'caravana', 'caçamba', 'rover', 'maquina'].map(w => ({ word: w, category: 'veiculos' })),
  // Peças de veículo (Vehicle parts)
  ...['volante', 'motor', 'pneu', 'roda', 'freio', 'acelerador', 'embreagem', 'farol', 'lanterna', 'retrovisor', 'parabrisa', 'radiador', 'bateria', 'vela', 'escapamento', 'carburador', 'chassi', 'amortecedor', 'placa', 'buzina', 'cinto', 'banco', 'capo', 'portamalas', 'painel', 'seta', 'cambio', 'marcha', 'radiador', 'alternador', 'bobina', 'bico', 'filtro', 'oleo', 'carter', 'pistao', 'biela', 'valvula', 'pedal', 'manopla', 'igniçao', 'chave', 'cilindrada', 'suspensao', 'mola', 'eixo', 'cubo', 'aro', 'calota', 'parachoque', 'grade', 'paralama', 'teto', 'janela', 'vidro', 'retrovisores', 'velocimetro', 'odometro', 'conta-giros', 'combustivel', 'tanque', 'escapamento', 'silenciador', 'escapar', 'tampa', 'radiadores', 'direçao', 'hidraulica', 'airbag', 'sensor', 'camera', 'limpador', 'antena', 'macaco', 'estepe', 'triangulo', 'extintor', 'engate', 'rabicho', 'bocal', 'porta', 'fechadura', 'retroiluminaçao'].map(w => ({ word: w, category: 'pecas' })),
  // Vias e Infraestrutura (Vias, highways, roads)
  ...['estrada', 'rodovia', 'avenida', 'rua', 'pista', 'asfalto', 'cruzamento', 'rotatoria', 'viaduto', 'ponte', 'tunel', 'passarela', 'calcada', 'acostamento', 'ciclovia', 'beco', 'travessa', 'marginal', 'ladeira', 'anel', 'trevo', 'bifurcaçao', 'esquina', 'praça', 'alameda', 'boulevard', 'autoestrada', 'pedagio', 'bueiro', 'sarjeta', 'guia', 'bloco', 'pavilhao', 'balao', 'retorno', 'entroncamento', 'rampa', 'calçamento', 'paralelepipedo', 'terra', 'cascalho', 'lama', 'buraco', 'cratera', 'pista', 'canteiro', 'central', 'faixa', 'reversivel', 'exclusiva', 'corredor', 'parada', 'ponto', 'abrigo', 'estacionamento', 'vaga', 'garagem', 'patio', 'terminal', 'estera', 'terminal', 'passagem', 'nivel', 'trilho', 'cancela', 'cancelas', 'guarita', 'valeta', 'redutor', 'radar', 'fotossensor', 'gantry', 'totem'].map(w => ({ word: w, category: 'vias' })),
  // Regras, Sinais, Documentos (Rules, signals)
  ...['semaforo', 'sinal', 'placa', 'tachao', 'lombada', 'pedagio', 'cone', 'cavalete', 'apito', 'habilitaçao', 'CNH', 'licenciamento', 'IPVA', 'seguro', 'multa', 'infraçao', 'bafometro', 'lei', 'codigo', 'regra', 'norma', 'decreto', 'limite', 'velocidade', 'radar', 'fiscalizaçao', 'vistoria', 'inspeçao', 'recurso', 'pontuaçao', 'suspensão', 'cassação', 'permissao', 'cadastro', 'registro', 'placa', 'chassi', 'categoria', 'exame', 'prova', 'teste', 'psicotecnico', 'medico', 'clinica', 'autoescola', 'instrutor', 'diretor', 'credenciamento', 'orgao', 'detran', 'denatran', 'contran', 'policia', 'PRF', 'guardas', 'agente', 'marronzinho', 'cet', 'talonario', 'notificaçao', 'advertencia', 'autuaçao', 'reincidencia', 'gravissima', 'grave', 'media', 'leve', 'pontos', 'recolhimento', 'apreensão', 'remoçao', 'patio', 'leilao', 'sinistro'].map(w => ({ word: w, category: 'sinais' })),
  // Padrões de Condução e Pessoas (Drivers, commuters...)
  ...['motorista', 'operador', 'piloto', 'pedestre', 'passageiro', 'carona', 'guarda', 'fiscal', 'policial', 'instrutor', 'agente', 'taxista', 'frentista', 'mecanico', 'despachante', 'ciclista', 'motociclista', 'caminhoneiro', 'carreteiro', 'bombeiro', 'socorrista', 'paramedico', 'oficial', 'patrulheiro', 'motoboy', 'entregador', 'uber', 'chofer', 'manobrista', 'valet', 'fretista', 'transeunte', 'cidadao', 'viajante', 'turista', 'estrangeiro', 'caroneiro', 'parceiro', 'dupla', 'patrulha', 'guia', 'inspetor', 'avaliador', 'perito', 'enfermeiro', 'medico', 'guinchador', 'asfaltador', 'varredor', 'gari', 'sinalizador', 'operador', 'central', 'tecnico', 'engenheiro', 'projetista', 'urbanista', 'planejador', 'corretor', 'vendedor', 'comprador', 'proprietario', 'dono', 'frotista'].map(w => ({ word: w, category: 'pessoas' })),
  // Ações de Condução e Trânsito (Actions as verbs)
  ...['dirigir', 'correr', 'frear', 'acelerar', 'ultrapassar', 'buzinar', 'estacionar', 'manobrar', 'capotar', 'bater', 'colidir', 'multar', 'licenciar', 'abastecer', 'calibrar', 'consertar', 'viajar', 'trafegar', 'circular', 'engarrafar', 'parar', 'aguardar', 'esperar', 'cruzar', 'retornar', 'dobrar', 'virar', 'contornar', 'desviar', 'escorregar', 'derrapar', 'bater', 'chocar', 'violentar', 'atropelar', 'socorrer', 'resgatar', 'chamar', 'sinalizar', 'piscar', 'iluminar', 'engatar', 'mudar', 'reduzir', 'puxar', 'soltar', 'apertar', 'girar', 'olhar', 'observar', 'prevenir', 'atentar', 'desatentar', 'dormir', 'cansar', 'beber', 'dirigir', 'examinar', 'vistoriar', 'checar', 'revisar', 'trocar', 'substituir', 'comprar', 'vender', 'alugar', 'locar', 'devolver', 'entregar', 'receber', 'pagar', 'cobrar', 'perdoar', 'recorrer', 'justificar', 'anular', 'validar', 'cadastrar', 'sinalizar', 'mecanizar', 'motorizar', 'personalizar', 'rebaixar', 'turbinar', 'lavar', 'limpar', 'polir', 'encerar', 'aspirar', 'mudar', 'transportar', 'carregar', 'descarregar', 'viajar', 'passear', 'commutar', 'deslocar', 'mover', 'avançar', 'recuar', 'dar-re', 'estacionar', 'vagar', 'ocupar', 'reservar', 'liberar'].map(w => ({ word: w, category: 'acoes' }))
];

const SEGURANCA_WORDS: PredefinedWord[] = [
  // Papéis de Defesa e Segurança (Roles)
  ...['segurança', 'guarda', 'policial', 'vigilante', 'patrulheiro', 'oficial', 'soldado', 'sargento', 'tenente', 'capitao', 'coronel', 'delegado', 'agente', 'detetive', 'vigia', 'bombeiro', 'salvavidas', 'socorrista', 'paramedico', 'guarda-costas', 'sentinela', 'batedor', 'escolta', 'portaria', 'porteiro', 'recepcionista', 'fiscal', 'inspetor', 'perito', 'investigador', 'promotor', 'juiz', 'advogado', 'defensor', 'carcereiro', 'policia', 'exercito', 'marinha', 'aeronautica', 'militar', 'civil', 'federal', 'municipal', 'metropolitana', 'florestal', 'rodoviaria', 'ambiental', 'brigada', 'milicia', 'tropa', 'comando', 'choque', 'bope', 'gerr', 'operador', 'tecnico', 'analista', 'gerente', 'diretor', 'chefe', 'coordenador', 'supervisor', 'auditor', 'consultor', 'especialista', 'zelador', 'porteiro', 'vigilantes', 'seguranças', 'policiais', 'guardas', 'defensores', 'investigadores'].map(w => ({ word: w, category: 'redes' })),
  // Equipamentos e Alarmes (Equipment)
  ...['alarme', 'camera', 'sensor', 'colete', 'capacete', 'cadeado', 'chave', 'cofre', 'cerca', 'portao', 'barreira', 'controle', 'sirene', 'farda', 'fuzil', 'pistola', 'revólver', 'algema', 'bastao', 'cassetete', 'spray', 'escudo', 'blindagem', 'extintor', 'mangueira', 'hidrante', 'mascara', 'luva', 'bota', 'lanterna', 'radio', 'comunicador', 'walkie-talkie', 'detector', 'metal', 'raio-x', 'scanner', 'biometria', 'fechadura', 'trinco', 'ferrolho', 'cadeados', 'chaves', 'cofres', 'portoes', 'grades', 'arame', 'farpado', 'concertina', 'muro', 'guarita', 'cabine', 'guarita', 'totem', 'catraca', 'cancela', 'cracha', 'cartao', 'acesso', 'biometrico', 'facial', 'digital', 'senha', 'codigo', 'token', 'chaveiro', 'dispositivo', 'arma', 'armamento', 'muniçao', 'bala', 'carregador', 'coldre', 'cinto', 'porta-algemas', 'fardamento', 'distintivo', 'insignia', 'patente', 'galao', 'quepe', 'boina', 'boné', 'jaqueta', 'impermeavel', 'coLETE', 'antibalas'].map(w => ({ word: w, category: 'equipamentos' })),
  // Ações de Proteção e Reação (Actions)
  ...['proteger', 'defender', 'patrulhar', 'rondar', 'vigiar', 'guardar', 'policiar', 'cuidar', 'prevenir', 'resgatar', 'socorrer', 'salvar', 'alertar', 'monitorar', 'inspecionar', 'vistoriar', 'fiscalizar', 'auditar', 'analisar', 'mitigar', 'evacuar', 'conter', 'isolar', 'bloquear', 'interceder', 'prender', 'deter', 'conduzir', 'algemar', 'revistar', 'buscar', 'apreender', 'confiscar', 'interrogar', 'investigar', 'rastrear', 'perseguir', 'capturar', 'imobilizar', 'neutralizar', 'combater', 'atirar', 'disparar', 'acionar', 'tocar', 'soar', 'burlar', 'invadir', 'roubar', 'furtar', 'agredir', 'assaltar', 'sequestrar', 'ameaçar', 'vandalizar', 'destruir', 'danificar', 'quebrar', 'violentar', 'infringir', 'violar', 'proibir', 'permitir', 'autorizar', 'validar', 'autenticar', 'verificar', 'checar', 'testar', 'ensaiar', 'treinar', 'simular', 'capacitar', 'instruir', 'orientar', 'alertar', 'avisar', 'notificar', 'reportar', 'comunicar', 'gravar', 'filmar', 'registrar', 'escrever', 'relatar', 'descrever', 'solucionar'].map(w => ({ word: w, category: 'acoes' })),
  // Leis, Protocolos, Espaços (Laws/protocols)
  ...['lei', 'codigo', 'regra', 'norma', 'protocolo', 'decreto', 'portaria', 'resoluçao', 'instruçao', 'ordem', 'serviço', 'missao', 'plano', 'projeto', 'estudo', 'analise', 'risco', 'vulnerabilidade', 'ameaça', 'perigo', 'incidente', 'acidente', 'sinistro', 'emergencia', 'crise', 'contingencia', 'continuidade', 'evacuaçao', 'resgate', 'bombeiros', 'hospital', 'clinica', 'delegacia', 'batalhao', 'quartel', 'base', 'posto', 'guarita', 'portaria', 'recepçao', 'estacionamento', 'patio', 'cadeia', 'presidio', 'penitenciaria', 'cela', 'tribunal', 'forum', 'ministerio', 'secretaria', 'governo', 'estado', 'municipio', 'uniao', 'naçao', 'patria', 'fronteira', 'limite', 'divisa', 'aduana', 'alfandega', 'porto', 'aeroporto', 'rodoviaria', 'estação', 'metro', 'trem', 'banco', 'agencia', 'caixa', 'cofre', 'shopping', 'loja', 'comercio', 'industria', 'fabrica', 'empresa', 'escritorio', 'condominio', 'predio', 'residencia', 'casa', 'lar', 'abrigo', 'asilo', 'creche', 'escola'].map(w => ({ word: w, category: 'espacos' })),
  // Segurança Geral (General safety words)
  ...['proteçao', 'defesa', 'segurança', 'alerta', 'ronda', 'vigilancia', 'guarda', 'cuidado', 'prevençao', 'socorro', 'alarme', 'perigo', 'risco', 'emergencia', 'acidente', 'colete', 'capacete', 'blindagem', 'barreira', 'controle', 'senha', 'protocolo', 'norma', 'regra', 'ordem', 'paz', 'tranquilidade', 'confiança', 'sirene', 'farda', 'patrulhas', 'rondador', 'vigias', 'inspeçoes', 'fuzis', 'pistolas', 'cofre-forte', 'bloqueador', 'contingencias', 'vigilancia-eletronica', 'segurança-privada', 'policiamento', 'delegacias', 'bombeiro-civil', 'brigadistas', 'salvamento', 'extintores', 'cavaletes', 'isolamento', 'detençao', 'bafometro', 'multas', 'advertencias'].map(w => ({ word: w, category: 'geral' }))
];

const TECNOLOGIA_WORDS: PredefinedWord[] = [
  // Dispositivos e Equipamentos (Devices / hardware)
  ...['computador', 'notebook', 'laptop', 'celular', 'smartphone', 'telefone', 'tablet', 'monitor', 'tela', 'teclado', 'mouse', 'gabinete', 'processador', 'memoria', 'disco', 'HD', 'SSD', 'placa-mae', 'placa-de-video', 'cooler', 'bateria', 'carregador', 'cabo', 'conector', 'fio', 'adaptador', 'fone', 'headset', 'microfone', 'caixa-de-som', 'impressora', 'copiadora', 'scanner', 'projetor', 'televisao', 'smart-tv', 'roteador', 'modem', 'switch', 'hub', 'servidor', 'mainframe', 'supercomputador', 'relogio-inteligente', 'smartwatch', 'oculos-vr', 'drone', 'camera-digital', 'webcam', 'pendrive', 'cartao-de-memoria', 'leitor', 'gravador', 'gabinete', 'fonte-de-alimentaçao', 'estabilizador', 'nobreak', 'filtro-de-linha', 'soquete', 'barramento', 'chip', 'circuito', 'resistor', 'transistor', 'capacitor', 'placa', 'hard驱动', 'hardware', 'periferico', 'maquina', 'dispositivo', 'aparelho', 'equipamento', 'terminal'].map(w => ({ word: w, category: 'hardware' })),
  // Arquivos, Redes, Conexões (Files, network)
  ...['rede', 'wifi', 'sinal', 'conexao', 'link', 'provedor', 'operadora', 'banda-larga', 'fibra-optica', 'satelite', 'antena', 'frequencia', 'canal', 'porta', 'protocolo', 'IP', 'DNS', 'URL', 'dominio', 'hospedagem', 'servidor', 'cliente', 'banco-de-dados', 'nuvem', 'cloud', 'armazenamento', 'backup', 'sincronizaçao', 'arquivo', 'documento', 'pasta', 'diretorio', 'caminho', 'atalho', 'formato', 'extensao', 'PDF', 'DOC', 'XLS', 'PPT', 'TXT', 'ZIP', 'RAR', 'EXE', 'APK', 'imagem', 'foto', 'video', 'audio', 'musica', 'som', 'player', 'mídia', 'streaming', 'download', 'upload', 'transferência', 'velocidade', 'trafego', 'banda', 'ping', 'latencia', 'estabilidade', 'pacote', 'dados', 'informaçao', 'metadados', 'banco', 'tabela', 'registro', 'campo', 'coluna', 'linha', 'consulta', 'query', 'sql', 'nosql', 'json', 'xml'].map(w => ({ word: w, category: 'redes' })),
  // Engenharia, Desenvolvimento, Web (Coding / dev)
  ...['codigo', 'programaçao', 'desenvolvimento', 'software', 'aplicativo', 'programa', 'site', 'pagina', 'portal', 'sistema', 'plataforma', 'framework', 'biblioteca', 'linguagem', 'python', 'javascript', 'html', 'css', 'php', 'java', 'ruby', 'go', 'rust', 'swift', 'kotlin', 'c++', 'typescript', 'algoritmo', 'variavel', 'funçao', 'classe', 'objeto', 'metodo', 'parametro', 'argumento', 'retorno', 'loop', 'condicional', 'if', 'else', 'while', 'for', 'switch', 'vetor', 'matriz', 'lista', 'pilha', 'fila', 'arvore', 'grafo', 'ponteiro', 'compilador', 'interpretador', 'editor', 'IDE', 'vscode', 'terminal', 'console', 'git', 'github', 'repositorio', 'commit', 'push', 'pull', 'branch', 'fork', 'merge', 'conflito', 'bug', 'erro', 'falha', 'debug', 'teste', 'testagem', 'automatizaçao', 'deploy', 'produçao', 'homologaçao', 'desenvolvedor', 'programador', 'engenheiro', 'analista', 'arquiteto'].map(w => ({ word: w, category: 'desenvolvimento' })),
  // Internet, IA e Segurança (Internet, IA, Cyber)
  ...['internet', 'tecnologia', 'informatica', 'firewall', 'antivirus', 'hacker', 'criptografia', 'biometria', 'token', 'inteligencia-artificial', 'algoritmo', 'servidor', 'backup', 'segurança-digital', 'antivirus', 'malware', 'virus', 'trojan', 'ransomware', 'spyware', 'adware', 'phishing', 'spam', 'firewalls', 'proxy', 'VPN', 'autenticaçao', 'autorizaçao', 'login', 'senha', 'usuario', 'perfil', 'registro', 'cadastro', 'criptografado', 'assinatura', 'certificado', 'chave-privada', 'chave-publica', 'blockchain', 'bitcoin', 'criptomoeda', 'carteira-digital', 'mineradora', 'inteligencia', 'artificial', 'robo', 'automata', 'chatbot', 'assistente', 'alexa', 'siri', 'assistant', 'gpt', 'gemini', 'modelo', 'rede-neural', 'deep-learning', 'machine-learning', 'aprendizado', 'dados', 'ciencia', 'big-data', 'analise', 'dashboard', 'grafico', 'indicador', 'metrica', 'KPI', 'relatorio', 'insight', 'previsao'].map(w => ({ word: w, category: 'ia_seg' })),
  // Ações Tecnológicas (Verbs)
  ...['programar', 'desenvolver', 'codificar', 'compilar', 'rodar', 'executar', 'testar', 'depurar', 'debugar', 'atualizar', 'instalar', 'desinstalar', 'configurar', 'formatar', 'reiniciar', 'desligar', 'ligar', 'conectar', 'desconectar', 'enviar', 'receber', 'baixar', 'carregar', 'salvar', 'gravar', 'deletar', 'excluir', 'apagar', 'copiar', 'colar', 'recortar', 'mover', 'renomear', 'pesquisar', 'buscar', 'encontrar', 'filtrar', 'ordenar', 'classificar', 'agrupar', 'compartilhar', 'publicar', 'hospedar', 'sincronizar', 'backup', 'restaurar', 'recuperar', 'criptografar', 'descriptografar', 'bloquear', 'desbloquear', 'proteger', 'atacar', 'burlar', 'invadir', 'corrigir', 'melhorar', 'otimizar', 'acelerar', 'medir', 'monitorar', 'analisar', 'visualizar', 'imprimir', 'digitalizar', 'escancear', 'projetar', 'interagir', 'clicar', 'digitar', 'rolar', 'deslizar', 'arrastar', 'soltar', 'pressionar', 'tocar', 'falar', 'ouvir', 'assistir', 'jogar', 'viciar', 'entreter', 'conectar', 'socializar', 'trabalhar', 'estudar'].map(w => ({ word: w, category: 'acoes' }))
];

const TRABALHO_WORDS: PredefinedWord[] = [
  // Profissões e Ocupações (Occupations)
  ...['trabalho', 'emprego', 'profissao', 'cargo', 'carreira', 'gerente', 'chefe', 'patrao', 'supervisor', 'coordenador', 'diretor', 'funcionario', 'colaborador', 'colega', 'equipe', 'time', 'auxiliar', 'assistente', 'analista', 'tecnico', 'especialista', 'consultor', 'assessor', 'secretario', 'recepcionista', 'atendente', 'vendedor', 'comprador', 'caixa', 'balconista', 'operador', 'motorista', 'entregador', 'motoboy', 'gari', 'varredor', 'limpador', 'porteiro', 'zelador', 'segurança', 'vigilante', 'bombeiro', 'policial', 'guarda', 'agente', 'fiscal', 'inspetor', 'perito', 'mecanico', 'eletricista', 'encanador', 'pedreiro', 'pintor', 'carpinteiro', 'marceneiro', 'serralheiro', 'vidraceiro', 'cozinheiro', 'garçom', 'barman', 'padeiro', 'confeiteiro', 'açougueiro', 'feirante', 'agricultor', 'pescador', 'jardineiro', 'veterinario', 'medico', 'enfermeiro', 'dentista', 'psicologo', 'fisioterapeuta', 'nutricionista', 'farmaceutico', 'biologo', 'quimico', 'fisico', 'matematico', 'engenheiro', 'arquiteto', 'desenhista', 'projetista', 'programador', 'desenvolvedor', 'professor', 'educador', 'instrutor', 'diretor', 'coordenador', 'reitor', 'advogado', 'juiz', 'promotor', 'defensor', 'jornalista', 'reporter', 'escritor', 'autor', 'editor', 'revisor', 'tradutor', 'interprete', 'artista', 'cantor', 'ator', 'musico', 'pintor', 'escultor', 'fotografo', 'cinegrafista', 'designer', 'ilustrador', 'publicitario', 'comunicador', 'contador', 'administrador', 'empresario', 'socio', 'parceiro'].map(w => ({ word: w, category: 'profissoes' })),
  // Escritório e Ferramentas (Work settings & tools)
  ...['escritorio', 'empresa', 'corporaçao', 'industria', 'fabrica', 'comercio', 'loja', 'agencia', 'filial', 'matriz', 'sede', 'departamento', 'setor', 'sala', 'mesa', 'cadeira', 'computador', 'notebook', 'telefone', 'ramal', 'celular', 'impressora', 'papel', 'caneta', 'lapis', 'caderno', 'bloco', 'pasta', 'gaveta', 'armario', 'arquivo', 'estante', 'quadro', 'agenda', 'calendario', 'relogio', 'carimbo', 'grampeador', 'clips', 'tesoura', 'regua', 'calculadora', 'sistema', 'software', 'planilha', 'excel', 'documento', 'contrato', 'oficio', 'memorando', 'relatorio', 'apresentaçao', 'email', 'mensagem', 'chamada', 'reuniao', 'sala-de-reunioes', 'auditorio', 'copera', 'refeitório', 'banheiro', 'elevador', 'corredor', 'entrada', 'recepçao', 'cracha', 'uniforme', 'colete', 'ferramenta', 'maquina', 'equipamento', 'dispositivo', 'painel', 'almoxarifado', 'estoque', 'deposito', 'galpao', 'estaleiro', 'canteiro', 'obra', 'campo', 'estação', 'posto', 'guarita', 'balcao', 'guiche', 'caixa', 'terminal', 'teclado', 'monitor'].map(w => ({ word: w, category: 'ferramentas' })),
  // Carreira e Finanças (Career and money)
  ...['salario', 'faturamento', 'lucro', 'prejuizo', 'renda', 'ganho', 'comissao', 'bonus', 'gratificaçao', 'beneficio', 'vale', 'alimentaçao', 'refeiçao', 'transporte', 'plano-de-saude', 'seguro-de-vida', 'aposentadoria', 'ferias', 'decimo-terceiro', 'FGTS', 'INSS', 'imposto', 'tributo', 'taxa', 'desconto', 'holerite', 'contracheque', 'carteira', 'trabalho', 'contrato', 'admissao', 'demissao', 'rescisao', 'aviso-previo', 'demissionario', 'desempregado', 'vaga', 'processo-seletivo', 'entrevista', 'curriculo', 'carreira', 'promoçao', 'aumento', 'transferencia', 'estagio', 'trainee', 'aprendiz', 'estagiario', 'trabalhador', 'empregado', 'patrao', 'empreendedor', 'autonomo', 'freelancer', 'terceirizado', 'estagiario', 'fisiologia', 'economia', 'finanças', 'investimento', 'capital', 'sociedade', 'açao', 'mercado', 'concorrencia', 'negocio', 'venda', 'compra', 'faturamento', 'lucratividade', 'custo', 'despesa', 'gasto', 'perda', 'rombo', 'falência', 'recuperaçao', 'acordo', 'parceria', 'negociaçao', 'fechamento', 'balanço', 'caixa'].map(w => ({ word: w, category: 'carreira' })),
  // Metas, Ações e Termos Laborais (Labour concepts / operations)
  ...['meta', 'projeto', 'produtividade', 'esforço', 'dedicaçao', 'competencia', 'serviço', 'tarefa', 'atividade', 'rotina', 'horario', 'turno', 'plantao', 'folga', 'reuniao', 'pauta', 'discussao', 'decisao', 'meta', 'objetivo', 'prazo', 'cronograma', 'planejamento', 'foco', 'resultado', 'rendimento', 'desempenho', 'avaliaçao', 'feedback', 'treinamento', 'desenvolvimento', 'capacitaçao', 'curso', 'palestra', 'workshop', 'convençao', 'evento', 'viagem', 'negocios', 'visita', 'cliente', 'fornecedor', 'parceiro', 'consumidor', 'usuario', 'publico', 'mercado', 'marca', 'produto', 'serviço', 'qualidade', 'padrao', 'processo', 'fluxograma', 'organograma', 'hierarquia', 'comunicacao', 'liderança', 'gestao', 'administraçao', 'operaçao', 'logistica', 'suporte', 'atendimento', 'vendas', 'marketing', 'compras', 'recursos-humanos', 'financeiro', 'juridico', 'comercial', 'tecnologia', 'produçao', 'faturamento', 'orçamento', 'custo', 'investimento', 'retorno', 'ROI', 'lucro', 'estrategia', 'inovacao', 'sucesso', 'crescimento', 'desafio', 'luta', 'esforço'].map(w => ({ word: w, category: 'acoes' })),
  // Geral Trabalho (General labor)
  ...['cargo', 'liderança', 'contrataçao', 'demissao', 'folga', 'ferias', 'competencia', 'rendimento', 'horas-extras', 'sindicato', 'greve', 'trabalhadores', 'escritorios', 'empresas', 'negocios', 'produtividades', 'colaboradores', 'profissionais', 'gestores', 'patroes', 'salarios', 'holerites', 'beneficios', 'promoçoes', 'carreiras', 'estagios', 'treinamentos', 'reunioes', 'projetos', 'metas', 'prazos', 'atividades', 'rotinas', 'operacoes', 'balanço', 'faturamentos', 'lucros', 'despesas', 'orçamentos', 'plataformas', 'suportes', 'esforços', 'dedicaçoes', 'eficiencia', 'eficacia', 'parcerias', 'acordos', 'contratos'].map(w => ({ word: w, category: 'geral' }))
];

const ALIMENTACAO_WORDS: PredefinedWord[] = [
  // Frutas, Vegetais, Temperos (Veggies / spices/ fruits)
  ...['maça', 'banana', 'laranja', 'morango', 'uva', 'limao', 'abacaxi', 'mamao', 'melancia', 'melao', 'pera', 'pessego', 'ameixa', 'cereja', 'morango', 'framboesa', 'amora', 'mirtilo', 'goiaba', 'manga', 'maracuja', 'caju', 'carambola', 'acerola', 'kiwi', 'caqui', 'figo', 'tamara', 'coco', 'castanha', 'nozes', 'amendoim', 'avelã', 'amendoa', 'alface', 'rucula', 'agriaõ', 'espinafre', 'couve', 'repolho', 'acelga', 'brocolis', 'couve-flor', 'cenoura', 'batata', 'mandioca', 'mandioquinha', 'beterraba', 'nabo', 'rabonete', 'cebola', 'alho', 'tomate', 'pimentao', 'berinjela', 'abobrinha', 'chuchu', 'quiabo', 'jilo', 'abobora', 'milho', 'ervilha', 'vagem', 'lentilha', 'grao-de-bico', 'feijao', 'arroz', 'trigo', 'aveia', 'centeio', 'cevada', 'soja', 'gengibre', 'hortela', 'manjericao', 'alecrim', 'salsa', 'cebolinha', 'coentro', 'louro', 'oregano', 'tomilho', 'canela', 'cravo', 'noz-moscada', 'cominho', 'curcuma', 'pimenta', 'sal', 'açucar', 'mel', 'azeite', 'oleo', 'vinagre', 'mostarda', 'ketchup', 'maionese'].map(w => ({ word: w, category: 'vegetais' })),
  // Refeições, Pratos e Lanches (Dishes / snacks)
  ...['lanche', 'almoço', 'jantar', 'cafe', 'sobremesa', 'doce', 'salgado', 'pao', 'bolo', 'pizza', 'hamburguer', 'salada', 'sopa', 'sushi', 'sashimi', 'temaki', 'pastel', 'coxinha', 'kibe', 'empada', 'esfiha', 'pao-de-queijo', 'misto-quente', 'bauru', 'hot-dog', 'lasanha', 'canelone', 'rondele', 'nhoque', 'espaguete', 'macarrao', 'miojo', 'risoto', 'sopa', 'caldo', 'creme', 'pure', 'farofa', 'feijoada', 'churrasco', 'grelhado', 'assado', 'frito', 'cozido', 'ensopado', 'strogonoff', 'parmegiana', 'escondidinho', 'panqueca', 'crepe', 'tapioca', 'omelete', 'quiche', 'torta', 'pudim', 'sorvete', 'gelatina', 'mousse', 'pave', 'brigadeiro', 'beijinho', 'trufa', 'bombom', 'chocolate', 'biscoito', 'bolacha', 'torrada', 'cereal', 'granola', 'iogurte', 'coalhada', 'queijo', 'requeijao', 'manteiga', 'margarina', 'geleia', 'pate', 'melado', 'rapadura'].map(w => ({ word: w, category: 'pratos' })),
  // Carnes, Proteínas, Bebidas (Proteins / drinks)
  ...['carne', 'frango', 'peixe', 'ovo', 'leite', 'presunto', 'mortadela', 'salame', 'bacon', 'linguica', 'salsicha', 'file', 'bife', 'costela', 'picanha', 'alcatra', 'contra-file', 'maminha', 'fraldinha', 'cupim', 'pernil', 'lombo', 'bacon', 'presunto', 'peito', 'asa', 'coxa', 'sobrecoxa', 'moela', 'coraçao', 'salmao', 'atum', 'sardinha', 'bacalhau', 'camarao', 'lagosta', 'caranguejo', 'lula', 'polvo', 'mexilhao', 'ostra', 'queijo', 'mussarela', 'prato', 'provolone', 'parmesao', 'gorgonzola', 'ricota', 'cottage', 'tofu', 'ovos', 'leite', 'creme-de-leite', 'leite-condensado', 'iogurte', 'bebida', 'agua', 'suco', 'refrigerante', 'cerveja', 'vinho', 'espumante', 'vodca', 'whisky', 'rum', 'gin', 'tequila', 'licor', 'cafe', 'cha', 'chimarrao', 'tereré', 'achocolatado', 'vitamina', 'milkshake', 'refrigerante', 'energetico', 'isotonico', 'agua-de-coco', 'caldo de cana'].map(w => ({ word: w, category: 'proteinas' })),
  // Cozinha, Sabores, Utensílios e Verbs (Kitchen and verbs)
  ...['comida', 'alimento', 'refeiçao', 'prato', 'ingrediente', 'cozinhar', 'assar', 'fritar', 'grelhar', 'cozer', 'ferver', 'refogar', 'temperar', 'salgar', 'adoçar', 'amassar', 'bater', 'misturar', 'mexer', 'cortar', 'picar', 'fatiar', 'ralar', 'descascar', 'lavar', 'limpar', 'limonada', 'cheiro', 'aroma', 'sabor', 'gosto', 'azedo', 'amargo', 'doce', 'salgado', 'picante', 'quente', 'frio', 'gelado', 'morno', 'delicioso', 'gostoso', 'saboroso', 'ruim', 'insosso', 'queimado', 'cru', 'passado', 'cozido', 'fome', 'sede', 'apetite', 'nutriçao', 'caloria', 'dieta', 'jejum', 'cafeteira', 'liquidificador', 'batedeira', 'fogao', 'forno', 'microondas', 'geladeira', 'freezer', 'panela', 'frigideira', 'assadeira', 'forma', 'prato', 'copo', 'taça', 'xicara', 'caneca', 'talher', 'garfo', 'faca', 'colher', 'concha', 'escumadeira', 'espatula', 'abridor', 'saca-rolhas', 'tabua', 'peneira', 'escorredor', 'bacia', 'pote'].map(w => ({ word: w, category: 'cozinha' })),
  // Saúde, Conceitos de Alimentação (Health concepts)
  ...['saude', 'nutriente', 'vitamina', 'proteina', 'carboidrato', 'lipidio', 'fibra', 'mineral', 'ferro', 'calcio', 'potassio', 'sodio', 'açucar', 'gordura', 'colesterol', 'glicose', 'caloria', 'peso', 'emagrecer', 'engordar', 'obesidade', 'desnutriçao', 'anemia', 'diabetes', 'hipertensao', 'alergia', 'intolerancia', 'gluten', 'lactose', 'vegano', 'vegetariano', 'organico', 'natural', 'saudavel', 'frescor', 'validade', 'conservaçao', 'higiene', 'digestao', 'estomago', 'intestino', 'figado', 'fome', 'saciedade', 'mastigaçao', 'deglutiçao', 'gula', 'banquete', 'festa', 'receita', 'cardapio', 'menu', 'chefe', 'cozinheiro', 'restaurante', 'culinaria', 'gastronomia', 'nutricionista', 'dieta', 'suplemento', 'capsula', 'cha'].map(w => ({ word: w, category: 'geral' }))
];

const ESPORTE_WORDS: PredefinedWord[] = [
  // Modalidades Esportivas (Modalities)
  ...['futebol', 'esporte', 'jogo', 'atletismo', 'basquete', 'volei', 'tenis', 'nataçao', 'corrida', 'ginastica', 'futsal', 'handebol', 'rugby', 'beisebol', 'futebol-americano', 'tenis-de-mesa', 'badminton', 'squash', 'padel', 'golfe', 'polo', 'hipismo', 'esgrima', 'tiro-com-arco', 'boxe', 'judô', 'caratê', 'taekwondo', 'jiu-jitsu', 'muay-thai', 'MMA', 'luta-livre', 'capoeira', 'surfe', 'skate', 'patinaçao', 'ciclismo', 'motociclismo', 'automobilismo', 'formula-1', 'kart', 'rali', 'canoagem', 'remo', 'vela', 'windsurf', 'kitesurf', 'esqui', 'snowboard', 'alpinismo', 'escalada', 'rapel', 'trilha', 'caminhada', 'pesca', 'caça', 'tiro', 'dardo', 'sinuca', 'bilhar', 'boliche', 'pebolim', 'ping-pong', 'xadrez', 'damas', 'trilha', 'gamao', 'baralho', 'poquer', 'truco', 'dominó', 'frescobol', 'beach-tenis', 'futevolei', 'altinha', 'peteca', 'maratona', 'triatlo', 'pentatlo', 'decatlo', 'crossfit', 'ioga', 'pilates', 'musculaçao', 'calistenia', 'aerobica', 'dança', 'balé', 'capoeira', 'parkour'].map(w => ({ word: w, category: 'modalidades' })),
  // Equipamentos e Uniformes (Sports gear)
  ...['bola', 'chuteira', 'uniforme', 'camisa', 'apito', 'cartao', 'raquete', 'rede', 'cesta', 'trave', 'aro', 'tabela', 'poste', 'mastro', 'bandeira', 'bandeirinha', 'cone', 'colete', 'meia', 'meiao', 'calçao', 'short', 'camiseta', 'agasalho', 'jaqueta', 'tenis', 'luva', 'capacete', 'oculos', 'toca', 'maio', 'biquini', 'bermuda', 'prancha', 'vela', 'canoa', 'barco', 'remo', 'skate', 'patins', 'patinete', 'bicicleta', 'quadro', 'roda', 'pneu', 'pedal', 'guidao', 'selim', 'freio', 'mola', 'bota', 'esqui', 'bastao', 'corda', 'mosquetao', 'cadeirinha', 'capacete', 'luvas', 'saco-de-pancadas', 'luva-de-boxe', 'protetor-bucal', 'caneleira', 'cotoveleira', 'joeleira', 'tornozeleira', 'faixa', 'quimono', 'espada', 'florete', 'sabre', 'mascara', 'alvo', 'arco', 'flecha', 'rifle', 'pistola', 'dardo', 'disco', 'martelo', 'peso', 'vara', 'barreira', 'plinto', 'argola', 'paralela', 'barra', 'trave', 'colchao', 'tatame', 'cronometro', 'marcador', 'placar'].map(w => ({ word: w, category: 'equipamentos' })),
  // Pessoas, Papéis e Posições (Roles / Positions)
  ...['jogador', 'atleta', 'goleiro', 'defensor', 'atacante', 'treinador', 'tecnico', 'arbitro', 'juiz', 'bandeirinha', 'torcedor', 'espectador', 'campeao', 'vice', 'perdedor', 'vencedor', 'rival', 'adversario', 'parceiro', 'companheiro', 'colega', 'capitao', 'reserva', 'titular', 'armador', 'lateral', 'zagueiro', 'volante', 'meia', 'centroavante', 'ponta', 'libero', 'levantador', 'bloqueador', 'sacador', 'receptor', 'rebatedor', 'arremessador', 'receptor', 'goleador', 'artilheiro', 'craque', 'idolo', 'mestre', 'professor', 'instrutor', 'preparador', 'fisioterapeuta', 'massagista', 'medico', 'psicologo', 'nutricionista', 'olheiro', 'empresario', 'patrocinador', 'presidente', 'diretor', 'gerente', 'supervisor', 'coordenador', 'delegado', 'comissario', 'cronometrista', 'anunciador', 'narrador', 'comentarista', 'reporter', 'fotografo', 'cinegrafista', 'gari', 'segurança', 'vigilante', 'maqueiro', 'gandula'].map(w => ({ word: w, category: 'posicoes' })),
  // Locais e Competições (Places & contexts)
  ...['estadio', 'campo', 'gramado', 'arena', 'ginasio', 'quadra', 'pista', 'piscina', 'raia', 'tablado', 'ringue', 'tatame', 'octogono', 'velodromo', 'autodromo', 'kartodromo', 'campo-de-golfe', 'hípica', 'mar', 'praia', 'rio', 'lago', 'bacia', 'represa', 'montanha', 'serra', 'trilha', 'rampa', 'neve', 'gelo', 'patinador', 'parque', 'clube', 'academia', 'centro-de-treinamento', 'campeonato', 'torneio', 'copa', 'liga', 'campeonatos', 'olimpiadas', 'mundial', 'regional', 'estadual', 'nacional', 'internacional', 'eliminatoria', 'classificaçao', 'qualificaçao', 'fase', 'rodada', 'grupo', 'chave', 'oitavas', 'quartas', 'semifinal', 'final', 'decisao', 'disputa', 'podio', 'ceremonia', 'medalha', 'ouro', 'prata', 'bronze', 'trofeu', 'taça', 'titulo', 'faixa', 'premio', 'diploma', 'honra', 'gloria', 'fama', 'sucesso'].map(w => ({ word: w, category: 'competicoes' })),
  // Ações, Verbos e Conceitos Gerais (Actions / feelings)
  ...['partida', 'torcida', 'gol', 'falta', 'penalti', 'escanteio', 'impedimento', 'drible', 'passe', 'chute', 'carrinho', 'treino', 'corrida', 'musculaçao', 'fisico', 'chutar', 'passar', 'correr', 'pular', 'saltar', 'nadar', 'surfar', 'skatar', 'pedalar', 'jogar', 'treinar', 'competir', 'vencer', 'ganhar', 'perder', 'empatar', 'disputar', 'combater', 'lutar', 'bater', 'bater-recorde', 'superar', 'esforçar', 'dedicar', 'focar', 'concentrar', 'vibrar', 'comemorar', 'gritar', 'torcer', 'vaiar', 'aplaudir', 'respeitar', 'cumprimentar', 'jogar-limpo', 'fair-play', 'doping', 'lesao', 'dor', 'fadiga', 'cansaço', 'recuperaçao', 'descanso', 'sono', 'nutriçao', 'hidrataçao', 'suor', 'calor', 'frio', 'vento', 'chuva', 'sol', 'clima', 'tempo', 'cronometro', 'estrada', 'viagem', 'hospedagem', 'concentraçao', 'nervosismo', 'ansiedade', 'medo', 'coragem', 'garra', 'raça', 'determinaçao', 'foco', 'força', 'fé', 'vitoria'].map(w => ({ word: w, category: 'acoes' }))
];

export const CONTEXT_DICTIONARY_THEMES: PredefinedThemeInfo[] = [
  {
    themeId: 'TRANSITO',
    themeName: 'Trânsito & Condução',
    icon: '🚗',
    description: 'Relacionado a veículos, rodovias, mecânica e regras de circulação.',
    secretWordCandidates: ['carro', 'motorista', 'estrada', 'rodovia', 'semaforo', 'freio', 'combustivel', 'pneu', 'volante', 'buzina', 'pedestre', 'multa', 'guincho', 'viagem', 'engarrafamento'],
    words: TRANSITO_WORDS
  },
  {
    themeId: 'SEGURANCA',
    themeName: 'Segurança & Defesa',
    icon: '🛡️',
    description: 'Relacionado à proteção, lei, patrulhamento civil/militar e mitigação de riscos.',
    secretWordCandidates: ['segurança', 'proteçao', 'patrulha', 'guarda', 'policial', 'vigilancia', 'alarme', 'camera', 'colete', 'capacete', 'fechadura', 'barreira', 'inspeçao', 'ordem', 'emergencia'],
    words: SEGURANCA_WORDS
  },
  {
    themeId: 'TECNOLOGIA',
    themeName: 'Tecnologia & Sistemas',
    icon: '💻',
    description: 'Relacionado à informática, internet, desenvolvimento de software e circuitos.',
    secretWordCandidates: ['computador', 'notebook', 'celular', 'internet', 'rede', 'wifi', 'sistema', 'software', 'aplicativo', 'codigo', 'programaçao', 'banco de dados', 'servidor', 'firewall', 'algoritmo'],
    words: TECNOLOGIA_WORDS
  },
  {
    themeId: 'TRABALHO',
    themeName: 'Trabalho & Negócio',
    icon: '👔',
    description: 'Relacionado a carreiras, escritório, rotina operacional, finanças e metas.',
    secretWordCandidates: ['trabalho', 'emprego', 'salario', 'carreira', 'escritorio', 'empresa', 'chefe', 'gerente', 'equipe', 'reuniao', 'projeto', 'meta', 'faturamento', 'lucro', 'contrato'],
    words: TRABALHO_WORDS
  },
  {
    themeId: 'ALIMENTACAO',
    themeName: 'Alimentação & Saúde',
    icon: '🍎',
    description: 'Relacionado a refeições, frutas, cozimento, culinária e bem-estar físico.',
    secretWordCandidates: ['comida', 'alimento', 'refeiçao', 'prato', 'lanche', 'almoço', 'jantar', 'cafe', 'suco', 'fruta', 'verdura', 'queijo', 'carne', 'panela', 'restaurante'],
    words: ALIMENTACAO_WORDS
  },
  {
    themeId: 'ESPORTE',
    themeName: 'Esporte & Lazer',
    icon: '⚽',
    description: 'Relacionado a modalidades esportivas, campeonatos, preparo físico e jogos coletivos.',
    secretWordCandidates: ['futebol', 'esporte', 'jogo', 'partida', 'campeonato', 'time', 'atleta', 'goleiro', 'treinador', 'juiz', 'estadio', 'bola', 'chuteira', 'torcida', 'gol'],
    words: ESPORTE_WORDS
  }
];
